### ISSUE TITLE
Install geo-portal with tomcat 7

### ISSUE THREAD

**Issue by minotogna** [slms4redd/chef-slms-portal#41]

**Comment by sgiaccio** [comment]
My last commit abf0eb13cb4fa64b0b8f462f6309c64b168d81f2 does exactly that :)

**Comment by Damianofds** [comment]
cool Stefano :) , so can we close the issue?

**Comment by sgiaccio** [comment]
Yes, going to do that, I also update the other (non production) dna.json, and documented it on the wiki.

Stefano
