### ISSUE TITLE
Issue on the demo Portal deployed by Chef

### ISSUE THREAD

**Issue by alessio-alfonsetti** [slms4redd/chef-slms-portal#47]
The demo portal deployed by Chef is not properly working. Following is the error stack trace:

exception

org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:617)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:1013)
	org.apache.jsp.WEB_002dINF.jsp.index_jsp._jspService(org.apache.jsp.WEB_002dINF.jsp.index_jsp:139)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:238)
	org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:262)
	org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1180)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:950)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:783)
	org.apache.jsp.index_jsp._jspService(org.apache.jsp.index_jsp:45)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

java.lang.NullPointerException
	org.apache.taglibs.standard.tlv.JstlBaseTLV.validate(JstlBaseTLV.java:178)
	org.apache.taglibs.standard.tlv.JstlCoreTLV.validate(JstlCoreTLV.java:134)
	org.apache.jasper.compiler.TagLibraryInfoImpl.validate(TagLibraryInfoImpl.java:913)
	org.apache.jasper.compiler.Validator.validateXmlView(Validator.java:1891)
	org.apache.jasper.compiler.Validator.validate(Validator.java:1859)
	org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:210)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:435)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:1013)
	org.apache.jsp.WEB_002dINF.jsp.index_jsp._jspService(org.apache.jsp.WEB_002dINF.jsp.index_jsp:139)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:238)
	org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:262)
	org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1180)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:950)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:783)
	org.apache.jsp.index_jsp._jspService(org.apache.jsp.index_jsp:45)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by Damianofds** [comment]
This is not an issue of the chef recipe but the related webapp installed. Please use the proper issue tracker.
